"""
Generates a daily markdown report from scored video data.
Saved to reports/YYYY-MM-DD.md and also updates reports/latest.md.
"""

import os
from datetime import date, datetime, timezone
from pathlib import Path

from . import config
from .scorer import label


def build_report(videos: list[dict], run_date: date | None = None) -> str:
    """Returns the full markdown report as a string."""
    if run_date is None:
        run_date = date.today()

    top_videos = [v for v in videos if v["views"] >= config.MIN_VIEWS][: config.TOP_N_VIDEOS]
    top_creators = _top_creators(videos)
    hot_hashtags = _hashtag_summary(videos)

    lines = [
        f"# Traveling Maine Coons -- TikTok Viral Tracker",
        f"**Date:** {run_date.strftime('%B %d, %Y')}",
        f"**Videos scanned:** {len(videos)}  |  "
        f"**Hashtags searched:** {len(config.HASHTAGS)}",
        "",
        "> This report surfaces TikTok content that can help grow the Traveling Maine Coons account.",
        "> HOT = high priority to engage with. STRONG = worth a like/comment/follow. WATCH = keep an eye on it.",
        "",
        "---",
        "",
        "## Top Videos to Engage With",
        "",
        "Engage means: like, comment something genuine, follow the creator, and ideally duet or stitch.",
        "",
    ]

    if not top_videos:
        lines.append("_No videos found matching your criteria today. Try again tomorrow!_")
    else:
        for i, v in enumerate(top_videos, 1):
            badge = label(v["score"])
            live_tag = " `LIVE`" if v.get("is_live") else ""
            lines += [
                f"### {i}. [{badge}]{live_tag} @{v['author_username']} -- {v['score']}/100",
                "",
                f"**Description:** {v['desc'][:200] or '_no description_'}",
                f"**Views:** {_fmt_num(v['views'])}  |  "
                f"**Likes:** {_fmt_num(v['likes'])}  |  "
                f"**Comments:** {_fmt_num(v['comments'])}  |  "
                f"**Shares:** {_fmt_num(v['shares'])}",
                f"**Followers:** {_fmt_num(v['author_followers'])}  |  "
                f"**Posted:** {_fmt_date(v['created_at'])}  |  "
                f"**Found via:** #{v.get('source_hashtag', '?')}",
                f"**Link:** {v['url']}",
                "",
                _score_bar(v["score_breakdown"]),
                "",
            ]

    lines += [
        "---",
        "",
        "## Creator Recommendations",
        "",
        "These creators are in the micro-influencer sweet spot -- big enough to matter, small enough to actually notice you.",
        "",
    ]

    for c in top_creators:
        lines += [
            f"- **@{c['username']}** ({_fmt_num(c['followers'])} followers) -- "
            f"avg score {c['avg_score']:.0f}, {c['video_count']} video(s) found today",
        ]

    lines += [
        "",
        "---",
        "",
        "## Hashtag Performance Today",
        "",
        "| Hashtag | Videos Found | Avg Score | Top Score |",
        "| --- | --- | --- | --- |",
    ]

    for h in hot_hashtags:
        lines.append(
            f"| #{h['tag']} | {h['count']} | {h['avg_score']:.0f} | {h['top_score']:.0f} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Your Action Checklist for Today",
        "",
        "- [ ] Visit the top 3 HOT videos and leave a genuine comment (mention Stevie or Jewels!)",
        "- [ ] Follow any HOT or STRONG creators you aren't following yet",
        "- [ ] Duet or stitch the highest-scoring video if the content fits",
        "- [ ] Check if any trending hashtags from today should be added to your next post",
        "- [ ] Note any live videos -- comment while they're live for maximum visibility",
        "",
        "---",
        f"_Generated by Traveling Maine Coons TikTok Viral Tracker on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}_",
    ]

    return "\n".join(lines)


def save_report(content: str, run_date: date | None = None) -> tuple[Path, Path]:
    """Writes the report to reports/YYYY-MM-DD.md and reports/latest.md."""
    if run_date is None:
        run_date = date.today()

    reports_dir = Path(config.REPORTS_DIR)
    reports_dir.mkdir(exist_ok=True)

    dated_path = reports_dir / f"{run_date.isoformat()}.md"
    latest_path = reports_dir / "latest.md"

    dated_path.write_text(content, encoding="utf-8")
    latest_path.write_text(content, encoding="utf-8")

    return dated_path, latest_path


# --- Helpers ---

def _top_creators(videos: list[dict]) -> list[dict]:
    from collections import defaultdict

    creators: dict[str, list] = defaultdict(list)
    for v in videos:
        creators[v["author_username"]].append(v)

    result = []
    for username, vids in creators.items():
        followers = vids[0]["author_followers"]
        if followers < config.CREATOR_SWEET_SPOT_MIN:
            continue
        result.append({
            "username": username,
            "followers": followers,
            "avg_score": sum(v["score"] for v in vids) / len(vids),
            "video_count": len(vids),
        })

    result.sort(key=lambda x: x["avg_score"], reverse=True)
    return result[: config.TOP_N_CREATORS]


def _hashtag_summary(videos: list[dict]) -> list[dict]:
    from collections import defaultdict

    tags: dict[str, list] = defaultdict(list)
    for v in videos:
        tags[v.get("source_hashtag", "unknown")].append(v["score"])

    result = []
    for tag, scores in tags.items():
        result.append({
            "tag": tag,
            "count": len(scores),
            "avg_score": sum(scores) / len(scores),
            "top_score": max(scores),
        })

    result.sort(key=lambda x: x["avg_score"], reverse=True)
    return result


def _score_bar(breakdown: dict) -> str:
    parts = []
    for key, val in breakdown.items():
        bar_len = round(val * 10)
        bar = "█" * bar_len + "░" * (10 - bar_len)
        label_str = key.replace("_", " ").title()
        parts.append(f"`{label_str}` {bar} {val:.0%}")
    return "  ".join(parts)


def _fmt_num(n: int) -> str:
    if n >= 1_000_000:
        return f"{n/1_000_000:.1f}M"
    if n >= 1_000:
        return f"{n/1_000:.1f}K"
    return str(n)


def _fmt_date(dt) -> str:
    if dt is None:
        return "unknown"
    return dt.strftime("%b %d, %Y")
